discourse/discourse-topic-voting

- config/locales/client.fr.yml
Some may need some change, need to see it in context to be sure.
> French translation

- app/controllers/discourse_feature_voting/votes_controller.rb
- assets/javascripts/discourse/widgets/add-super-vote.js.es6
- assets/javascripts/discourse/widgets/remove-super-vote.js.es6
- assets/javascripts/discourse/widgets/remove-vote.js.es6
- assets/javascripts/discourse/widgets/upgrade-vote.js.es6
- assets/javascripts/discourse/widgets/vote-box.js.es6
- plugin.rb
Per https://meta.discourse.org/t/discourse-feature-voting/40121/129
> Fix supervotes-left calculation

- config/locales/client.nl.yml
On behalf of the Dutch company [Socioneers](http://www.socioneers.com), I would like to contribute the Dutch translation file.
> Dutch translation file (config/locales/client.nl.yml).

- config/locales/server.es.yml
I went ahead and updated the Spanish language file to match the English version.
I didn't use the TL0, TL1, etc. variables because wasn't easy to phrase the sentence.  
I don't have this plugin running right now, so couldn't test it - just thought I could contribute.  Feel free to merge or discard.
> Updates Spanish language file

- plugin.rb
Fix bug introduced at 67c847fc5aff0b8e6b1c2ff1553a01775051472a  and initially reported at https://meta.discourse.org/t/rake-task-for-merging-users/89086/29.
@featheredtoast I'd love a review of this.
> FIX: Do not count nil or blank values as votes

- assets/javascripts/discourse/pre-initializers/extend-category-for-voting.js.es6
- assets/javascripts/discourse/widgets/vote-button.js.es6
- assets/stylesheets/common/feature-voting.scss
- assets/stylesheets/desktop/feature-voting.scss
- assets/stylesheets/mobile/feature-voting.scss
- adds color / font variables and removes hardcoded colors and font-sizes
- removes unused star icon
- changes vote count tag from hyperlink to span
- adds core CSS classes to vote button
- makes who-voted positioned on mobile to match desktop
- CSS clean up
> UX: clean up CSS and remove unused elements / code

- assets/javascripts/discourse/pre-initializers/extend-category-for-voting.js.es6
- config/locales/client.en.yml
To be merged after discourse/discourse#7158.
> FEATURE: Allow 'Votes' as default topic sort order.

- plugin.rb
> FIX: ensure compatibility with older Discourse

- assets/javascripts/discourse/initializers/discourse-voting.js.es6
This is a follow up to commit discourse/discourse@57624983917 and
e437b603bd26d3913de557e8eb8175d810f974dd.
> FIX: Use correct variable name

- assets/javascripts/discourse/initializers/discourse-voting.js.es6
- plugin.rb
Few if statements to ensure plugin works with a stable discourse. Completely obsolete once 2.6.0 will become stable
> FIX: backwards compatibility with stable discourse 2.5.0

- assets/javascripts/discourse/widgets/vote-button.js.es6
Should be a tiny bit easier to follow now.
> DEV: Refactor buttonTitle

- spec/voting_spec.rb
See https://github.com/discourse/discourse/pull/11205
> DEV: Cleanup DiscourseEvent handler after spec

- plugin.rb
- spec/requests/search_controller_spec.rb
See https://github.com/discourse/discourse/commit/4b3f65bb26c9d72f85b10f69956cd8ab75978d0a
> FIX: Search advanced order after changes in core.

- assets/javascripts/discourse/initializers/discourse-voting.js.es6
Depends on https://github.com/discourse/discourse/pull/13813
> UX: Add quick search suggestion

- assets/javascripts/discourse/initializers/discourse-voting.js.es6
- plugin.rb
Reverts https://github.com/discourse/discourse-voting/commit/18794557dbb48cf469981b763be044b33f5d0d26
> DEV: Remove some old code

- .discourse-compatibility
- assets/javascripts/discourse/routes/user-activity-votes.js.es6
- config/locales/client.en.yml
- test/javascripts/acceptance/user-activity-votes-test.js.es6
Shows this when a user hasn't voted for any topic yet:
and this when a user is looking at the page of another user:
> FEATURE: Improve blank page syndrome

- plugin.rb
- spec/fabricators/topic_vote_count_fabricator.rb
- spec/fabricators/vote_fabricator.rb
- spec/serializers/basic_category_serializer_spec.rb
- spec/serializers/topic_list_item_serializer_spec.rb
- spec/serializers/topic_view_serializer_spec.rb
Serializer tests need to be added before we make some renames.
> DEV: Backfill tests before rename

- .github/workflows/plugin-tests.yml
- spec/system/page_objects/pages/category.rb
- spec/system/page_objects/pages/topic.rb
- spec/system/voting_spec.rb
To cover for the rename. Dependent on https://github.com/discourse/discourse/pull/18972
There's currently only one js test for the whole repo 😿
> DEV: Add system tests

- app/controllers/discourse_topic_voting/votes_controller.rb
- app/jobs/regular/vote_reclaim.rb
- app/jobs/regular/vote_release.rb
- lib/discourse_topic_voting/categories_controller_extension.rb
- lib/discourse_topic_voting/category_extension.rb
- lib/discourse_topic_voting/list_controller_extension.rb
- lib/discourse_topic_voting/topic_extension.rb
- lib/discourse_topic_voting/topic_query_extension.rb
- lib/discourse_topic_voting/user_extension.rb
- plugin.rb
- spec/requests/votes_controller_spec.rb
- Define extension modules
- Use different files instead of plugin.rb
- Make sure plugin is disabled according to the setting
> DEV: Update plugin to match latest guidelines

- assets/javascripts/discourse/templates/connectors/category-custom-settings/feature-voting-settings.hbs
- assets/javascripts/discourse/templates/connectors/user-activity-bottom/user-voted-topics.hbs
- package.json
- yarn.lock
> DEV: Use angle bracket syntax

- app/controllers/discourse_topic_voting/votes_controller.rb
- config/locales/client.en.yml
- lib/discourse_topic_voting/web_hook_extension.rb
- plugin.rb
- spec/fabricators/topic_voting_hook_fabricator.rb
- spec/requests/votes_controller_spec.rb
Triggers a custom webhook event when a topic receives an upvote.
Follow up to https://github.com/discourse/discourse/pull/23072.
> FEATURE: trigger a custom webhook on upvotes

- app/controllers/discourse_topic_voting/votes_controller.rb
- spec/requests/votes_controller_spec.rb
Add `topic_slug` to the upvote event payload
> FEATURE: add topic_slug to the upvote event payload

- assets/stylesheets/common/topic-voting.scss
> UX: improved alignment for title voting

- spec/system/voting_spec.rb
AdminSettings changed to AdminSiteSettings
in discourse/discourse@83361b2fc529f2a6e05c2660b80d6a647d7debd7
> DEV: Update name of page object

- README.md
This reverts commit 771e63feca85e281a40060a52af5ce0703a80717.
> Revert "DEV: Deprecate the plugin (#246)"
