discourse/discourse-topic-voting

- config/locales/client.de.yml
- config/locales/server.de.yml
I had to do a more colloquial, yet correct translation. Correct me if I'm wrong, but the reason is that in https://github.com/discourse/discourse-voting/blob/master/assets/javascripts/discourse/widgets/vote-button.js.es6#L32 and https://github.com/discourse/discourse-voting/blob/master/assets/javascripts/discourse/widgets/vote-button.js.es6#L49 the key `voting.vote_title` ("Vote") is used as a noun _and_ a verb. In German it's two different words: "Stimme" ("vote" as noun) and "Abstimmen" ("to vote"). As a workaround I used the more or less common Anglicism "Vote", which is also equally spelled as a noun and verb in German.
To make a long story short: The translation should suffice, but if im right with my notion, maybe this has to be changed in the future to provide a better translation.
> Add german localization

- app/controllers/discourse_voting/votes_controller.rb
- app/jobs/onceoff/clean_dup_null_votes.rb
- plugin.rb
- spec/requests/votes_controller_spec.rb
- spec/voting_spec.rb
* Fixes a bug where the job for releasing/reclaiming votes wasn't enqueued when topic is closed (reported [here](https://meta.discourse.org/t/votes-not-being-released-after-close/96394?u=osama))
* Somehow a user may have duplicate votes to the same topic and all of the dup votes count towards their quota. This will ignore duplicate votes.
* Topic vote counter didn't count archived votes.
* Moving a topic to a different category didn't release/reclaim votes correctly, this PR fixes that.
* Get rid of vote records with `nil` topic_id
* Adds a onceoff job to clean up mess.
> FIX: release/relcaim votes when topic is closed, clear duplicate and null votes

- assets/javascripts/discourse/pre-initializers/extend-category-for-voting.js.es6
- assets/javascripts/discourse/templates/connectors/extra-nav-item/votes.hbs
- assets/javascripts/discourse/templates/connectors/extra-nav-item/votes.js.es6
It used to be a link using the "votes" filter mode which was overwritten
by default category sort order.
Instead, one should use the 'order' query parameter to sort the topic
list by number of votes.
This commit also removes some dead code.
> FIX: Use correct URL for sorting by votes.

- assets/stylesheets/common/feature-voting.scss
- assets/stylesheets/desktop/feature-voting.scss
- assets/stylesheets/mobile/feature-voting.scss
This PR refactors the plugin's CSS.
Notable changes:
1. changes most `px` units to `em` units (the ones left as `px` have good reasons to be)
2. uses flexbox for improved alignment
3. removes some unused styles (super votes)
4. improves support for RTL locales (this is TEMP see https://meta.discourse.org/t/moving-the-voting-box-to-the-right-side-of-the-screen/126752 for more details. I added these to the very bottom for easy removal in the future once the main cause is fixed.
5. minor fixes like preventing the pop-up menu from overlapping with user-cards
Before (LTR - desktop)
After (LTR -  desktop)
Before (RTL - desktop) 
After (RTL - desktop)
Before (LTR - mobile)
After (LTR - mobile) 
Before (RTL - mobile)
After (RTL - mobile)
Before (user-card overlap)
After (user-card overlap)
The …
> REFACTOR: plugin CSS cleanup

- app/jobs/onceoff/voting_ensure_consistency.rb
- plugin.rb
Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364
> FIX: Use top-level namespace for base classes

- plugin.rb
- spec/voting_spec.rb
Addressing [this thread](https://meta.discourse.org/t/deleteing-a-topic-with-votes-not-releasing-votes/130009/7)
The specs looks short, but all we really need to test is whether or not the `VoteReclaim` and `VoteRelease` jobs are run, because they are tested and bear the responsibility of updating the user count properly.
[Supporting PR](https://github.com/discourse/discourse/pull/8144) for discourse main app
> FIX: user vote count is updated when topics are trashed/restored

- config/locales/server.en.yml
- plugin.rb
- spec/ensure_consistency_spec.rb
- spec/voting_spec.rb
Merging two votes with topics will edit the moderator post describing
the move operation, to include information about how many votes were
moved and why some votes were not (because user already voted for the
destination topic).
Example:
>  FEATURE: Let user know how many votes were moved.

- plugin.rb
Currently, if you got that plugin installed and change code in development in Discourse, you will see an error like:
`undefined method `can_vote?'`
A reason for that was incorrectly defined `reloadable_patch` block. That block defines everything which should be reloaded by ActiveSupport::Reloader if code is changed.
because that was not included in that block
```
class ::Category
def self.can_vote?(category_id)
end
end
```
method `can_vote?` was not anymore available.
> FIX: include all reloadable parts of the plugin

- assets/javascripts/discourse/widgets/vote-button.js.es6
Problem was that we are adding `hidden` class to popup and jQuery `toggle()` function is not handling that properly. Therefore I decided to use `toggleClass` in that case and it works pretty well.
The bug was mentioned here - https://meta.discourse.org/t/voting-plugin/157676/8
> FIX: the ability to remove the vote

- Gemfile
- Gemfile.lock
- plugin.rb
- spec/voting_spec.rb
I was able to reproduce a bug where votes were not properly moved when merging two topics together. We were only checking duplicate votes if either both votes were either active or archived, and not a mix of the two. As a result, there were cases where the plugin was trying to move votes that already existed on an open topic, causing the merge to partially fail with a duplicate index error.
What this PR does is as follows:
1. Cleaned up the logic so it's more readable. Previously it was duplicative and difficult to read.
2. We're now checking if a user has a vote on Topic A (active or archived) and Topic B (active or archived) that we're properly deleting the origin vote and keeping the destination vote instead of trying to merge in a duplicate. (This caused the original bug described …
> FIX: Stop trying to merge duplicate votes

- assets/javascripts/discourse/widgets/vote-button.js.es6
When the user used all the votes we should not send a request to create a vote. We should only display information about votes.
The bug was mentioned on meta: https://meta.discourse.org/t/the-vote-button-should-be-disabled-when-the-limit-is-reached/68902
> FIX: don't send xhr request when vote limit is reached

- assets/javascripts/discourse/widgets/vote-count.js.es6
`/voting/who` path has `ensure_logged_in` so clicking the vote count to see who voted triggered http requests that ended with 403 error. Now, users are asked to log in, just like when clicking the "vote" button.
> FIX: Ask to log in before requesting who_voted

- db/post_migrate/20201003141123_remove_votes_of_deleted_users.rb
- lib/discourse_voting/user_extension.rb
There are some assumptions in the code that `vote.user` exists. It makes sense to boop the votes out of existence when their owner is destroyed.
> FIX: Delete the votes on user removal

- assets/javascripts/discourse/widgets/vote-count.js.es6
We should use `/u/:username` instead of `/users/:username`
> FIX: the correct path to user profile

- app/models/discourse_voting/category_setting.rb
- app/models/discourse_voting/topic_vote_count.rb
- app/models/discourse_voting/vote.rb
- lib/discourse_voting/topic_extension.rb
- spec/lib/topic_extension_spec.rb
The `Topic#update_vote_count` method should be concurrency-safe to prevent unique constraint violation errors when multiple processes try to insert a topic_votes_count record for the same topic simultaneously.
Signed-off-by: OsamaSayegh <asooomaasoooma90@gmail.com>
> FIX: Upsert topic votes count atomically

- plugin.rb
- spec/serializers/post_serializer_spec.rb
Changing category settings would not always unhide the like button
because the model would not be updated on the client side until a full
page refresh.
> FIX: Always serialize can_vote for first posts

- spec/voting_spec.rb
The issue was that when we were moving the post using posts[1,2]
the ordering was not always consistent, so sometimes we moved post
number 1 for the topic and sometimes post number 2.
If post number 1 was moved, the PostMover just creates a copy of it
in the destination topic, as the OP of the topic cannot be moved.
If post number 2 was moved, then PostMover _actually_ moves it to
the destination topic, and thus leaves only one post behind in
the original topic, which causes the original topic to be closed
and makes the spec fail.
This change ensures that post number 1 is the one we are moving
in the test, making sure the order is constant.
> DEV: Fix flaky spec

- lib/discourse_voting/topic_extension.rb
- plugin.rb
We shouldn't add vote fields for personal messages since users can't vote there. If we include then it's creating an N+1 issue in the `private-messages-all` endpoint.
> PERF: exclude vote fields in `topic-list-item` serializer for PMs.

- plugin.rb
- spec/lib/topic_query_spec.rb
If the number of votes is the same and the second order-by column is not specified then Postgres makes no guarantee about what the ordering will be.
https://meta.discourse.org/t/some-topics-disappear-when-sorting-by-votes/213669
> FIX: add second order by column to preserve order while paging.

- lib/discourse_voting/categories_controller_extension.rb
- spec/requests/categories_controller_spec.rb
The voting plugin's category setting is broken per https://meta.discourse.org/t/223880 and https://meta.discourse.org/t/223753
This PR fixes the reported issue.
Earlier the code was checking `params[:custom_fields].delete(:enable_topic_voting) == "true"` which assumes we'll get a `"true"` string but we don't. This value is populated from
https://github.com/discourse/discourse-voting/blob/3d9f4c2996c98cca33380981fbac14bdcc702006/assets/javascripts/discourse/templates/connectors/category-custom-settings/feature-voting-settings.hbs#L5
and the controller converts this to a ruby boolean and hence the condition fails.
> FIX: handle boolean correctly on server

- lib/discourse_voting/categories_controller_extension.rb
- spec/requests/categories_controller_spec.rb
On the category settings page if the voting plugin is enabled and user
clicks “Save Category” button then the database record for the
`discourse_voting_category_settings` table is deleted and recreated
every time the button is pressed. This commit checks for existing record
and prevents creation of new database record
> FIX: do not recreate database record for category setting

- app/models/discourse_voting/category_setting.rb
- spec/lib/topic_query_spec.rb
- spec/models/discourse_voting/category_setting_spec.rb
Since the move to separate tables the category changes to voting plugin was not being logged. This commit fixes that.
> FIX: logs category setting changes when voting is enabled/disabled

- assets/javascripts/discourse/templates/connectors/user-activity-bottom/user-voted-topics.hbs
The plugin outlet is already wrapped in a `li` tag.
https://github.com/discourse/discourse/blob/c0037dc0f06f08bd050aedc8aad97d1f05b322ab/app/assets/javascripts/discourse/app/templates/user/activity.hbs#L69
> UX: Avoid double `li` tag in user-activity-bottom outlet

- plugin.rb
- spec/serializers/current_user_serializer_spec.rb
- spec/serializers/topic_view_serializer_spec.rb
Also switch to using `add_to_serializer` to prevent evaluating certain serializer attributes if the plugin is off.
> DEV: More tests before rename

- lib/discourse_topic_voting/categories_controller_extension.rb
- lib/discourse_topic_voting/category_extension.rb
- spec/requests/categories_controller_spec.rb
What is the problem?
Discourse core already declares a `has_one :category_setting`
association so this plugin is overriding that association which is not
what we want.
What is the solution?
Since this plugin adds a category setting model of its own, we can
simply rename the association to avoid the conflict with core.
> DEV: Rename `has_one :category_setting` as it clashes with core

- app/models/discourse_topic_voting/category_setting.rb
- spec/models/discourse_voting/category_setting_spec.rb
Follow-up to #148.
Without this inverse declaration ActiveRecord gets confused in the presence of two `CategorySetting` classes.
> DEV: Add inverse declaration for  association

- plugin.rb
- spec/serializers/category_serializer_spec.rb
Currently, if a hoster has this plugin installed but disabled, they will get no Category custom fields, which is bad.
What this means is that despite checking this option in category settings, this bug will cause it not to be shown as checked.
This PR fixes the custom_field bug.
> FIX: Don't remove custom fields when adding a new one to category serializer

- app/controllers/discourse_topic_voting/votes_controller.rb
- config/locales/client.en.yml
- spec/requests/votes_controller_spec.rb
- Adds a new `topic_unvote` event which triggers the `topic_voting` webhook when a user unvotes the post
- Changes the description for the webhook to reflect the new trigger
- Adds a test for the new `topic_unvote` event
> FEATURE: add topic_unvote event to trigger topic_voting webhook

- plugin.rb
- spec/voting_spec.rb
We were triggering the `vote_reclaim` job on scenarios where votes shouldn't be reclaimed:
- editing a closed/archived/deleted topic's `tracked_topic_fields` (`title`/`archetype`/`tags`) field while not changing the `category_id`
- moving a closed/archived/deleted topic to a different, votes-enabled category
- unarchiving a closed topic
- opening an archived topic
Tests were also added covering these use cases.
> FIX: avoid reclaiming un-reclaimable votes

- lib/discourse_topic_voting/categories_controller_extension.rb
- spec/requests/categories_controller_spec.rb
Bug report: https://meta.discourse.org/t/-/289850
Solution ref: https://stackoverflow.com/questions/34794697
`custom_fields` might not be passed if the request is via API. We need to handle the case so that there's no error thrown(NoMethodError is being thrown currently).
I didn't include a test case because its not simple to test. Using `put` inside `expect {}` doesn't raise the error in the controller up to the invocation it seems?
> FIX: use safe navigation operator for params

- spec/system/voting_spec.rb
The user being tested is an admin. Admins ~~are always~~ should by right be TL4 in production. The default number of votes for TL4 users is 10, not 4.
> DEV: Amend misleading test regarding remaining votes

- plugin.rb
- spec/voting_spec.rb
Ensures merging topics also merge votes regardless of the voters' visibility (when `voting_show_who_voted` site setting is `false`), bypassing this check from the previously used `orig.who_voted`:
https://github.com/discourse/discourse-topic-voting/blob/f9654ee1b6342ed1a11c23003bcb4a05b6f3c9e9/lib/discourse_topic_voting/topic_extension.rb#L48-L52
> FIX: merge votes regardless of voters' visibility

- db/post_migrate/20240717071658_update_data_explorer_topic_voting_queries.rb
Following the table migrations from https://github.com/discourse/discourse-topic-voting/pull/196, plenty of data explorer queries will probably stop reflecting updated values.
This PR updates data explorer queries to use the new table name.
> DEV: Update data explorer queries to new table if exists

- .discourse-compatibility
- assets/javascripts/discourse/widgets/remove-vote.js
This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update deprecated Font Awesome icon names

- assets/javascripts/discourse/initializers/discourse-topic-voting.js
Along with https://github.com/discourse/discourse/pull/31264 — allows a category with voting enable to select "Votes" as the Default Topic List value.
> FEATURE: add "Votes" option to category topic list settings

- test/javascripts/acceptance/user-activity-votes-test.js
Re-enables the tests disabled in 4a85501052d849529f7d061df633af44bae9a087, now that https://github.com/discourse/discourse/pull/33455 has been merged
> DEV: re-enable empty state test
